### ISSUE TITLE
css

### ISSUE THREAD

**Issue by sodiqit** [n0sfer666/ui-kit__formElements#77]
Все что можно сделать через css - лучше делать через него, а не засорять разметку декоративными элементами.
![image](https://user-images.githubusercontent.com/47000555/152297435-6d22378d-4af1-4706-86ed-f025bfdf3a7a.png)

**Comment by n0sfer666** [comment]
Сделал так:
HTML:
```pug
    .booking__total
      h2.booking__total-text Итого
      h2.booking__total-text #{currency}
      h2.booking__total-text.js-booking__total-text #{total}
```
CSS:
```scss
  &__total {
    display: block;
    width: 100%;
    max-height: 24px;
    @include fix-overflow;

    &:after {
      $dots: '...............................';
      $manyDots: $dots $dots $dots $dots;
      content: $manyDots;
      display: block;
      color: $dark-shade-25;
      line-height: 28px;
      white-space: nowrap;
      overflow: hidden;
    }
```
